# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET
on:
  push:
    branches: [ "release" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: src/MiNET/MiNET.Console
      run: dotnet restore
    - name: Test
      working-directory: src/MiNET/MiNET.Console
      run: dotnet test --no-build --verbosity normal

  release:
    permissions: write-all
    name: Publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: src/MiNET/MiNET.Console/minet.zip
        asset_name: MiNET.zip
        tag: ${{ github.ref }}
        release_name: MiNET-CobwebSMP 1.0.1 (1.20.50)
        body: ${{ github.event.head_commit.message }}
